branch-defaults:
  master:
    environment: circleci-demo-dev
    group_suffix: null
  parallel-job:
    environment: circleci-demo-dev
    group_suffix: null
deploy:
  artifact: target/circleci-demo.jar
global:
  application_name: circleci-demo
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Java 8
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
