version: 2.1

executors:
  docker-jdk:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    working_directory: ~/circleci-demo
  docker-jdk-postgres:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
      - image: circleci/postgres:11.2-alpine-ram
        environment:
          POSTGRES_DB: circlecidemo
          POSTGRES_USER: circlecidemo
          POSTGRES_PASSWORD: circlecidemo
    working_directory: ~/circleci-demo

jobs:
  build:
    executor: docker-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run: mvn dependency:go-offline
      - run: mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Save artifacts
          command: |
            mkdir -p ~/artifacts/
            find . -type f -regex ".*/target/.*jar" -exec cp {} ~/artifacts/ \;
          when: always
      - store_artifacts:
          path: ~/artifacts
      - persist_to_workspace:
          root: .
          paths:
            - target/*
  test:
    executor: docker-jdk-postgres
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run: mvn verify
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - persist_to_workspace:
          root: .
          paths:
            - target/*
  sonar:
    executor: docker-jdk
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - sonar-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - sonar-v1-{{ .Branch }}-
            - sonar-v1-
      - run:
          name: Sonar analysis
          command: |
            mvn sonar:sonar \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.organization=${SONAR_ORGANIZATION} \
              -Dsonar.host.url=${SONAR_HOST} \
              -Dsonar.login=${SONAR_LOGIN}
      - save_cache:
          paths:
            - ~/.m2
            - ~/.sonar/cache
          key: sonar-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
  deploy:
    executor: docker-jdk
    steps:
      - checkout
      - attach_workspace:
          at: .

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - sonar:
          requires:
            - test
      - deploy-approval:
          type: approval
          requires:
            - sonar
      - deploy:
          requires:
            - deploy-approval
