version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
      - image: circleci/postgres:11.2-alpine-ram
        environment:
          POSTGRES_DB: circlecidemo
          POSTGRES_USER: circlecidemo
          POSTGRES_PASSWORD: circlecidemo
    working_directory: ~/circleci-demo
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run: mvn dependency:go-offline
      - run: mvn install
      - run:
          name: Sonar analysis
          command: |
            mvn sonar:sonar \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.organization=${SONAR_ORGANIZATION} \
              -Dsonar.host.url=${SONAR_HOST} \
              -Dsonar.login=${SONAR_LOGIN}
      - save_cache:
          paths:
            - ~/.m2
            - ~/.sonar/cache
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - run:
          name: Save artifacts
          command: |
            mkdir -p ~/artifacts/
            find . -type f -regex ".*/target/.*jar" -exec cp {} ~/artifacts/target/ \;
          when: always
      - persist_to_workspace:
          root: .
          paths:
            - target/*
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/artifacts

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
